"""Content-addressed sufficient statistics and deployment-specific profiles."""
from __future__ import annotations

import hashlib
import json
import os
import tempfile
from pathlib import Path

from sglang.srt.dllm.dws_wsl import DWSWSLProfile, canonical, copy_probe_sidecar
from sglang.srt.dllm.profile_common import atomic_json

# Set this to a persistent directory when serving across restarts.
DEFAULT_CACHE_ROOT = os.environ.get("DWS_PROFILE_CACHE", "/tmp/dllm_wls_cache")


def cache_path(profile, cost, root=DEFAULT_CACHE_ROOT):
    identity = {"trajectory_keys": profile.payload["shape"]["trajectory_keys"], "cost_keys": cost}
    return Path(root) / ("profile-" + hashlib.sha256(canonical(identity)).hexdigest() + ".json")


def statistics_filename(profile):
    return "wls-stats-" + profile.payload["shape"]["fit"]["statistics_id"] + ".npz"


def read_statistics(profile, *, root=DEFAULT_CACHE_ROOT, profile_path=None):
    from sglang.srt.dllm.cost_fit import FitState, deployment_identity

    if not profile.is_full_fit:
        return None
    candidates = [Path(root) / statistics_filename(profile)]
    if profile_path:
        candidates.insert(0, Path(profile_path).parent / statistics_filename(profile))
    for path in candidates:
        if path.is_file():
            state = FitState.load(path)
            if (state.digest != profile.payload["shape"]["fit"]["statistics_id"]
                    or state.identity != deployment_identity(profile, profile.payload["scale"]["cost_keys"])):
                raise ValueError("profile/statistics digest or deployment mismatch")
            return state
    raise ValueError("missing WLS statistics sidecar: " + statistics_filename(profile))


def save_statistics(profile, state, root=DEFAULT_CACHE_ROOT):
    import numpy as np
    from sglang.srt.dllm.cost_fit import deployment_identity

    if (state.digest != profile.payload["shape"]["fit"]["statistics_id"]
            or state.identity != deployment_identity(profile, profile.payload["scale"]["cost_keys"])):
        raise ValueError("cannot save statistics belonging to another profile")
    directory = Path(root)
    directory.mkdir(parents=True, exist_ok=True)
    readme = directory / "README.md"
    start, end = "<!-- dws-cost-profiles:start -->", "<!-- dws-cost-profiles:end -->"
    description = (
        start + "\n# DWS full cost profiles and sufficient statistics\n\n"
        "Generated by the Appendix E WLS fitter. The input contract is individually "
        "measured CUDA-event profiling requests; original trace paths/dataset identity "
        "are not retained and are unknown unless documented separately. "
        "Raw historical traces and model weights are not stored by the fitter.\n"
        "profile-*.json is the latest published profile for an exact model/decoding/"
        "hardware/TP signature; measured_at records its Unix timestamp. "
        "wls-stats-*.npz contains version-1 additive training and held-out statistics "
        "(G, r, q, scalar sums and support), keyed by their SHA-256 digest.\n"
        "Keep each profile with its referenced statistics and optional probe-suite "
        "sidecar to resume fitting. The JSON records the selected smoothing weights, "
        "candidate grid, validation scores, timing convention and deployment keys. "
        "Statistics require NumPy to read and SciPy to refit; serving the fitted "
        "cost kernel uses neither. Historical raw timings cannot be reconstructed.\n" + end + "\n")
    previous = readme.read_text(encoding="utf-8") if readme.exists() else ""
    if start in previous and end in previous:
        before, rest = previous.split(start, 1)
        _, after = rest.split(end, 1)
        contents = before + description.rstrip("\n") + after
    else:
        contents = previous + ("\n\n" if previous else "") + description
    readme.write_text(contents, encoding="utf-8")
    target = directory / statistics_filename(profile)
    fd, temporary = tempfile.mkstemp(prefix=target.name + ".", dir=directory)
    try:
        with os.fdopen(fd, "wb") as handle:
            np.savez_compressed(handle, **state.arrays())
        os.replace(temporary, target)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return target


def copy_statistics_sidecar(profile, profile_path, output_dir):
    if profile.is_full_fit:
        state = read_statistics(profile, profile_path=profile_path)
        return save_statistics(profile, state, output_dir)
    return None


def read_profile_cache(profile, cost, root=DEFAULT_CACHE_ROOT):
    try:
        path = cache_path(profile, cost, root)
        cached = DWSWSLProfile.from_mapping(json.loads(path.read_text()))
        if (not cached.is_full_fit or cached.payload["scale"]["cost_keys"] != cost
                or cached.payload["shape"]["trajectory_keys"] != profile.payload["shape"]["trajectory_keys"]):
            return None
        read_statistics(cached, root=root, profile_path=path)
        return cached
    except (OSError, ValueError, KeyError, TypeError):
        return None


def newest_profile(profile, cost, root=DEFAULT_CACHE_ROOT):
    cached = read_profile_cache(profile, cost, root)
    if cached is not None and (not profile.is_full_fit or profile.payload["scale"]["cost_keys"] != cost
                              or cached.payload["scale"]["measured_at"] > profile.payload["scale"].get("measured_at", 0)):
        return cached
    return profile


def write_profile_cache(profile, state, *, root=DEFAULT_CACHE_ROOT, profile_path=None):
    import fcntl

    path = cache_path(profile, profile.payload["scale"]["cost_keys"], root)
    save_statistics(profile, state, root)
    copy_probe_sidecar(profile, profile_path or path, root)
    with path.with_suffix(".lock").open("a") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        atomic_json(path, profile.to_dict())


def choose_profile(profile, cost, mode="auto", cache_root=DEFAULT_CACHE_ROOT):
    if mode not in {"auto", "force", "off"}:
        raise ValueError("invalid cost probe mode")
    if mode == "off":
        return profile  # Explicit compatibility escape hatch, including legacy fits.
    if mode == "force":
        return None
    selected = newest_profile(profile, cost, cache_root)
    if selected.is_full_fit and selected.payload["scale"]["cost_keys"] == cost:
        return selected.with_scale({**selected.payload["scale"], "probe_state": "reused"})
    return None
